In [1]:
from tqdm import tqdm
import os
import cv2
import random
import numpy as np
import pandas as pd
import add_attributes

GLASSES_ADDED_FOLDER='glasses_added'
GENERATED_GLASSES_CSV='generated_glasses.csv'
BEARD, MOUSTACHE, GLASSES,FILENAME = 0, 1, 2,3
SEED = 42
random.seed(SEED)

params= {
    'attribute': GLASSES
}

In [4]:
# loading dataset

def load_dataset(dataset_folder='../utkface', labels_csv='../labels_prof.csv'):
    X, y = [], []
    for line in tqdm(open(labels_csv)):
        filename, beard, moustache, glasses = line.split(',')
        beard, moustache, glasses = int(beard), int(moustache), int(glasses)
        img = cv2.imread(os.path.join(dataset_folder, filename), cv2.IMREAD_UNCHANGED)
        X.append((img))
        y.append((beard, moustache, glasses,filename))

    _X = np.array(X)
    _y = np.array(y)
    assert (len(_X) == len(_y))
    del X
    del y
    return _X, _y

In [5]:
X,Y = load_dataset()

9770it [00:12, 772.71it/s]


In [6]:
#Eseguire questo blocco una sola volta dopo il load dataset
"""[15 44 71]
[ 87 116  90]
[219 214 215]
[209 201 201]
"""
X=X[:800]
Y=Y[:800]

from sklearn.utils import shuffle
X, Y = shuffle(X, Y, random_state=42)

for i in range(4):
    print(X[i,0,0])

[15 44 71]
[ 87 116  90]
[219 214 215]
[209 201 201]


In [10]:
#Carica Tommaso 
x=X[:400]
y=Y[:400]

In [7]:
#Carica Francesco
x=X[400:800]
y=Y[400:800]

In [8]:
male_glasses=[]
female_glasses=[]
for i in range (len(add_attributes.glasses_png)):
    gender=int(add_attributes.glasses_png[i][1].split('_')[0])
    if gender==0:
        male_glasses.append(add_attributes.glasses_png[i][0])
    elif gender==1:
        female_glasses.append(add_attributes.glasses_png[i][0])
    else:
        male_glasses.append(add_attributes.glasses_png[i][0])
        female_glasses.append(add_attributes.glasses_png[i][0])


        


ext='.jpg.chip.jpg'


padded=np.zeros((800,800,3), dtype=np.uint8)

beard=[]
moustache=[]
glass=[]
filename=[]
j=0
for i in range(len(x)):

    _x = x[i]

    if int(y[i][GLASSES]) == 0:

        splittedFilename=y[i][FILENAME].split('_')
        age=int(splittedFilename[0])
        
        if age >= 5:
            gender=int(splittedFilename[1])
            if gender==0:
                glasses = random.sample(male_glasses,k=1)[0]
            else:
                glasses = random.sample(female_glasses,k=1)[0]
                
            padded[300:500,300:500,:]=_x 
            z=add_attributes.add_glasses(padded, glasses)
            z=z[300:500,300:500,:]

            cv2.imshow('added', z)
            k=cv2.waitKey(0)
            if k==ord('y'):
                beard.append(y[i,BEARD])
                moustache.append(y[i,MOUSTACHE])
                glass.append(1)
                file=y[i,FILENAME].split('.')[0]+'_glasses'+ext
                filename.append(file)
                cv2.imwrite(GLASSES_ADDED_FOLDER+'/'+file,z)
                j=j+1
                print('salva')
            if k==ord('n'):
                print('scartato')
            if k==ord('q'):
                break

df=pd.DataFrame(data={'filename':filename, 'beard':beard,'moustaches':moustache,'glasses':glass})
df.to_csv(f"{GENERATED_GLASSES_CSV}", index=False, header=False)
cv2.destroyAllWindows()

salva
salva
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
salva
salva
scartato
salva
scartato
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
salva
salva
scartato
salva
salva
salva
salva
salva
salva
salva
salva
salva
salva
s